### ISSUE TITLE
参加者の表記が「◯ / ◯人」のときと「残り◯人」のときがある。どういうルール？

### ISSUE THREAD

**Issue by kdmsnr** [doorkeeper/doorkeeper-support#10]

**Comment by pwim** [comment]
今A/B test中です。
半分の参加者はいつも「◯ / ◯人」を表示します。
他の半分はイベントの参加率が60%以内場合、「残り◯人」を表示します。

**Comment by kdmsnr** [comment]
A/Bテスト中なら仕方ないけど……「残り◯人」は見づらいので、設定できるようにしてほしい。

**Comment by pwim** [comment]
$B%"%$%G%"$O%$%Y%s%H$,>/?M?t$@$C$?$i!"?M$O;22C$7$?$/$J$$$3$H$G$9!#(B
$B!V;D$j"~?M!W$NLdBj$O8@MU$G$9$+!#(B
$B$b$7$/$O!"$$$D$b!V"~(B / $B"~?M!WI=<($7$?$$$G$9$+!#(B

2013/4/8 KADO Masanori notifications@github.com:

**Comment by pwim** [comment]
あら、emailで返事しましたら、文字化けになってしまいます。

---

アイデアはイベントが少人数だったら、人は参加したくないことです。
「残り◯人」の問題は言葉ですか。
もしくは、いつも「◯ / ◯人」表示したいですか。

**Comment by kdmsnr** [comment]
いつも「◯ / ◯人」がいいです。
でも、「残り◯人」がいいという人もいると思います。
3つ設定できるといいのでは？（1.「◯ / ◯人」2.「残り◯人」3.自動切り替え）

**Comment by pwim** [comment]
どうして、角さんなら、「◯ / ◯人」のほうがいいがいいでしょうか。

**Comment by kdmsnr** [comment]
情報が多いほうがいいじゃないですか。

「残り◯人」がいいと思う人は、人数を知られたくないとか、人気がないのがバレたくないとか、そういうことじゃないかなあ。

**Comment by pwim** [comment]
わかりました。「イベントの参加者を公開する」のオプションを使っているイベントは「◯ / ◯人」のように表示したいと思いましたが、角さんのイベントはそのオプションを使えなくなりましたね。どうしてでしょうか。

**Comment by kdmsnr** [comment]
運営者としては、情報はできるだけオープンにしたいので「◯ / ◯人」がいいです。
参加者の情報については、オープン／クローズのどちらがいいか判断できないので、安全側のクローズにしています。

**Comment by pwim** [comment]
わかりました。
では、参加者は自分で情報がオープン／クローズが決めたら、いいですね。

**Comment by kdmsnr** [comment]
:+1:

**Comment by kakutani** [comment]
> 参加者は自分で情報がオープン／クローズが決めたら、いいですね

:+1:

**Comment by pwim** [comment]
A/Bテスト終了しました。いつも「◯ / ◯人」を使います。
