### ISSUE TITLE
参加者リストを「表示する/しない」をイベント単位で個別に設定したい

### ISSUE THREAD

**Issue by kakutani** [doorkeeper/doorkeeper-support#11]
(本来はコミュニティが異なるのかもしれませんが)たとえば、

「ESMセミナー ビジネス価値の発見とデリバリー -BABOKとAgileによる実現-」は参加者のリストをwebに出したくありません(ビネス色が強いので)。
http://esminc.doorkeeper.jp/events/1966

いっぽう、
「第1回 Funtoo Linux インストール講習会」は参加者をwebに出したいです(勉強会の色が強い)。
http://esminc.doorkeeper.jp/events/3547

いまの仕様だと、参加者のリストを出すのか、出さないのかでDoorkeeperで
コミュニティを分けることになります。

ruby-no-kai とrubykaigi が分かれている理由のひとつでもあります
(rubykaigiについては、localeを分けたいというのも理由ですが)。

**Comment by kdmsnr** [comment]
ref #10

**Comment by pwim** [comment]
@kakutani #10 の通り、主催者じゃなくて、参加者は自分で参加者リストに表示するかどうか、Funtoo LinuxのようなイベントでもESMセミナーでも大丈夫ですよね。

**Comment by kakutani** [comment]
@pwim なるほど。#10 の通り、参加者が决められるというのは :+1: です。

その場合は、自分を参加者リストに公開する/しないのデフォルトの設定はやはりコミュニティ単位で决めることになりますか?

参加者が公開する/しないを選べるのだとしても、
デフォルトの設定をどちらにするのかイベント単位で决められるといいな、と思いました。

**Comment by pwim** [comment]
オプションがあるかどうか、まだ決めてません。
Doorkeeperは参加者を公開したいイベントをターゲットしているので、デフォルトは公開すると思いますが、設定が必要か検討します。
