### ISSUE TITLE
新しいイベント管理ページからイベント編集へのリンクがほしい

### ISSUE THREAD

**Issue by kakutani** [doorkeeper/doorkeeper-support#13]
たとえば、

https://manage.doorkeeper.jp/groups/rubykaigi/events/3509

のページに、

https://manage.doorkeeper.jp/groups/rubykaigi/events/3509/edit

へのリンクがありません。

そのため、イベント管理(?)ページから、
いちいち手でeditをURL欄に入力するかコミュニティのページから辿らねばならず、
不便に感じています。

ご検討よろしくお願いします。

**Comment by pwim** [comment]
すみません、なんかマージのときミスでした。編集リンクを復活しました。

**Comment by kakutani** [comment]
I've confirmed :fried_shrimp:
