### ISSUE TITLE
申し込みメールに返信するときに、参加登録者に返信したい

### ISSUE THREAD

**Issue by kakutani** [doorkeeper/doorkeeper-support#15]
お問い合わせメールは(当然ですが)問い合わせた人に返信できます。

申し込みメールにorganizerへの連絡事項を書いてくれた人に返信しようとすると、
reply-toが info@doorkeeper.jp になっているので、ひと手間かけないと参加者に返信できません。

しかも、メール内の「参加登録者」のHTMLは、返信用ではないので、
メールアドレスをコピペするのも大変です(chrome + gmailの場合)。

参加登録者からの問い合わせなので、
もう少しスムーズにやりとりできるようになるとうれしいです。

**Comment by pwim** [comment]
フィードバックありがとうございます。
申し込みメールにreply-toヘッダ設定するように更新しました！
