### ISSUE TITLE
Twitterフィードがなくなった？

### ISSUE THREAD

**Issue by kdmsnr** [doorkeeper/doorkeeper-support#16]

**Comment by pwim** [comment]
widget$B$O(Bdeprecated$B$5$l$^$7$?!#(B
https://dev.twitter.com/blog/api-v1-retirement-final-dates

$B?7$7$$(Bwidget$B$O(Btwitter$B$N%&%'%V%5%$%H$N%"%+%&%s%HItJ,$+$i0l$D0l$D$NEPO?$,I,MW$J$N$G!";H$($^$;$s!#(B

**Comment by kdmsnr** [comment]
mojibake!

**Comment by pwim** [comment]
すみません、androidのgmailから返事すると文字化けになります。

widgetはdeprecatedされました。 https://dev.twitter.com/blog/api-v1-retirement-final-dates

新しいwidgetはtwitterのアカウント設定部分から一つ一つ作らないといけないので、DoorkeeperのようにDynamic Widget作れません。
