### ISSUE TITLE
コミュニティのメンバーに対してメールを送れる機能があってほしい

### ISSUE THREAD

**Issue by snoozer05** [doorkeeper/doorkeeper-support#19]
ひとつのイベントへの参加者にではなくて、コミュニティのメンバーに対してご案内を出したいという場面がありました。コミュニティのメンバーに対してメールを送れる機能があるととても助かります！

**Comment by pwim** [comment]
時期は未定ですが、たくさんの主催者から要望があるので、追加する予定があります。

**Comment by kdmsnr** [comment]
:+1:

**Comment by pwim** [comment]
お待たせしました。
http://www.doorkeeper.jp/news/2014/4/21/messages-to-community
