### ISSUE TITLE
チケットごとに人数を設定したい

### ISSUE THREAD

**Issue by kdmsnr** [doorkeeper/doorkeeper-support#20]

**Comment by pwim** [comment]
はい、その機能も追加したいんです。

**Comment by silkycove** [comment]
+1

**Comment by lasershow** [comment]
+1

**Comment by pwim** [comment]
チケットごとに人数を設定する機能を調査しまして、複数のユースケースがあります。一つのケースを解決しまして、プライベートベータでリリースしました。

試したかったら、info@doorkeeper.jp までどんな種類のチケットで使いたいを教えてください。

**Comment by pwim** [comment]
お待たせしました。チケットごとに定員を設定できる機能を正式にリーリスしました。

https://www.doorkeeper.jp/news/2017/9/5/per-ticket-type-limits
