### ISSUE TITLE
割引コードを発行したい

### ISSUE THREAD

**Issue by kdmsnr** [doorkeeper/doorkeeper-support#26]
same as: http://help.peatix.com/customer/ja/portal/articles/976445

**Comment by kakutani** [comment]
+1

**Comment by pwim** [comment]
[イベントに割引コードが設定できるようになりました！](http://www.doorkeeper.jp/news/2014/5/16/promo-code)

**Comment by kakutani** [comment]
super!

**Comment by kakutani** [comment]
@pwim とても便利そうだと思いました! (RubyKaigiで使おう)

いまは
- 無料
- 割引率

のオプションですが、
- 割引額

も設定できるようになると、計算しやすいので助かります。

**Comment by pwim** [comment]
@kakutani そうですね。実現するには、「割引率」のほうが簡単でしたが、割引額も追加したいと思います。
ちなみに、RubyKaigiのRFPはいつ始めるでしょうか？

**Comment by kakutani** [comment]
@pwim RubyKaigiのチケットの販売は6月になってしまいそうです。
スポンサーや、talkは、もうすぐです。

**Comment by pwim** [comment]
@kakutani わかりました、頑張ります。もちろん、今年もスタッフさせてください。

**Comment by pwim** [comment]
@kakutani 割引額を追加しました！
