### ISSUE TITLE
メールアドレスの出力形式

### ISSUE THREAD

**Issue by kdmsnr** [doorkeeper/doorkeeper-support#27]
Doorkeeperに登録できるように `姓 名 <email@example.com>` でエクスポートしたい。

**Comment by pwim** [comment]
リクエストありがとうございます。
Google Docs、Numbers、Excelなどでエクスポートを編集したら、以下のコードでそのフォーマットに変更出来ると思います。

```
=A2&" <"&B2&">"
```

**Comment by kdmsnr** [comment]
エクスポートしたものは「そのまま」インポートできるようにしたほうがよいです。

**Comment by pwim** [comment]
インポートの場合、メールアドレスだけでも大丈夫です。
名前はコミュニティのメンバーの名前だけではなくて、Doorkeeperのアカウントの名前になっているので、メールアドレスだけでインポートするして、名前を表示します。

**Comment by kdmsnr** [comment]
`姓 名 <email@example.com>` のサンプルに意味がないようなら、変更したほうがよいと思いました。

**Comment by pwim** [comment]
わかりづらくてすみません。
今までDoorkeeperを使ってないかたにインポートする場合、姓名を使っています。
エクスポートして、インポートする場合、全員はすでにDoorkeeperで姓名があるので必要ではありません。
将来はインポート機能をリニューアルしたいので、そのときにもっとわかりやすい方法を検討します。
