### ISSUE TITLE
参加者の人数だけ表示したい

### ISSUE THREAD

**Issue by kdmsnr** [doorkeeper/doorkeeper-support#28]
「参加者の公開」をしていなくても、「あとn人参加できます。」は表示したい。

**Comment by pwim** [comment]
[参加者は自分でリストに公開かどうかを決める](http://www.doorkeeper.jp/news/2014/3/17/participant-privacy)ので、どうして公開したくないでしょうか。

**Comment by kdmsnr** [comment]
オプションで設定できるのだから、理由に関係なく設定してもいいですよね。

これは「参加者の公開」で「あとn人参加できます。」の表示が決まるのは変だという意味のチケットです。

**Comment by kdmsnr** [comment]
コミュニティで「参加者の公開」をオンにした場合、過去のイベントもすべて公開されませんか？「参加者は自分でリストに公開かどうかを決める」のは理解していますが、デフォルトで「オン」になっていたら困ります。

**Comment by pwim** [comment]
参加者の公開をオンにした場合、過去のイベントに参加したの人のデフォルトはオフです。新しいイベントに申込すると、オンに設定出来ます。なお、メンバーの設定なので、オンに設定したら、過去のイベントも表示し、いつでもプロフィールを編集して、オフに設定出来ます。

**Comment by kdmsnr** [comment]
ありがとうございます。理解しました。

それとは別に、「参加者の公開」と「残り人数の公開」は別オプションにしたほうがよいです。

**Comment by kdmsnr** [comment]
`/events`には人数が表示されているので、詳細画面にも表示するか、両方表示しないかのいずれかですね。

**Comment by kdmsnr** [comment]
「参加者の公開」をオンにしたけど、「あとn人参加できます。」は表示されませんでした。

**Comment by pwim** [comment]
わかりづらくてすみません。公開された参加者がないと、表示されていません。

**Comment by kdmsnr** [comment]
とにかく「あとn人参加できます。」を表示したいです！

**Comment by bash0C7** [comment]
:+1: 
http://rubykaigi.doorkeeper.jp/events/14570 でも、申し込み参加者数と、残り何人参加できるかを、参加しようか考えている人向けへの情報として提示したいと思ってます。

**Comment by kakutani** [comment]
:+1:

**Comment by pwim** [comment]
@kdmsnr のアイデアの通り、いつも「あとX人参加できます。」を表示します。参加者０人やメンバー公開しないときも表示します。申込が終了の場合、表示しません。

**Comment by kdmsnr** [comment]
:+1:

**Comment by bash0C7** [comment]
:+1: :+1: :+1:
