### ISSUE TITLE
コミュニティに入会するフォームがほしい

### ISSUE THREAD

**Issue by kdmsnr** [doorkeeper/doorkeeper-support#31]
イベントの「お申し込みフォーム」のように、コミュニティの「お申し込みフォーム」がほしい。

**Comment by pwim** [comment]
コミュニティーのメンバーではなかったら、申し込みできます。

![community-member](https://cloud.githubusercontent.com/assets/30756/5949277/5b2f0cb0-a78f-11e4-93bb-9ad3bae48bb1.png)

メンバーでしたら、表示しません。

**Comment by kdmsnr** [comment]
そうではなく、「お申し込みフォームの設置」がやりたいです。

**Comment by pwim** [comment]
http://waicrew.doorkeeper.jp/member/new へリンクするのはどうでしょうか。

**Comment by kdmsnr** [comment]
ログインしないとできなさそうなので、クローズでいいです。
