### ISSUE TITLE
参加者のエクスポート：削除した事前アンケートはいらない

### ISSUE THREAD

**Issue by kdmsnr** [doorkeeper/doorkeeper-support#39]

**Comment by pwim** [comment]
質問をアーカイブする機能を追加しました。
アーカイブすると参加者にその質問を表示しないが、エクスポートなどで表示します。
今日、アーカイブされた質問を削除する機能を追加しました。
削除したら、エクスポートに表示しません。

**Comment by kdmsnr** [comment]
削除しても、メール通知には残っている。

**Comment by pwim** [comment]
すみません、不具合なおしました。
