### ISSUE TITLE
領収書データ表示機能がほしい

### ISSUE THREAD

**Issue by kdmsnr** [doorkeeper/doorkeeper-support#43]
eventregist みたいに

**Comment by kdmsnr** [comment]
peatixも「領収データ」というのがあるらしい。
http://help.peatix.com/customer/portal/articles/825927

@pwim これは対応できないですか？

**Comment by kdmsnr** [comment]
そもそもDoorkeeperで集金しているのだから、領収書データを出せと言われたら断れない義務っぽい。
https://invoice.moneyforward.com/receipts-lp/basic/receipts-issuance-duty

**Comment by pwim** [comment]
peatixはクレジットカードの場合、領収書が発行しなさそうです。

> クレジットカードの場合
> カード会社から送付される「ご利用明細書」や「引き落とし明細書」が領収書に相当しますので、こちらをご利用ください。

コンビニ/ATM払いの場合のみ発行すると思います。

**Comment by pwim** [comment]
リンクありがとうございます。

> クレジットカードでの支払いの場合は、直接の金銭のやり取りがなく、信用の取引であるため、領収書の発行義務はありません。また、表題が領収書となっていても、領収書としては認められないため、顧客の希望に応じて領収書を発行する場合には、印紙は不必要です。なお、但し書き欄には、クレジットカードを利用した旨を記載します。

クレジットカードの場合、領収書発行しなくても良さそうです。

**Comment by kdmsnr** [comment]
peatixは領収書は出さないけど、領収データは出すみたい。せめてこれくらいは対応してほしい。

**Comment by pwim** [comment]
わかりました。領収データは法人的な意味がありませんが、領収書っぽいものですね。検討します。

**Comment by pwim** [comment]
[領収データ](http://support.doorkeeper.jp/article/36-receipt)を表示するようになりました。
