### ISSUE TITLE
割引コードの一覧がほしい

### ISSUE THREAD

**Issue by kdmsnr** [doorkeeper/doorkeeper-support#45]

**Comment by pwim** [comment]
リクエストありがとうございました。各イベントがすでに管理画面で一覧がありますけど、なんの一覧ほしいでしょうか？

**Comment by kdmsnr** [comment]
作成した割引コードの一覧が欲しいです（ないよ？）

**Comment by pwim** [comment]
作成した割引コードがなかったら、「新規割引コード作成」にリダイレクトします。もしかして、イベントはまだコードがないでしょうか。

コードがあったら以下の一覧を表示します。

![screen shot 2016-12-12 at 10 13 08](https://cloud.githubusercontent.com/assets/30756/21085291/9c138f92-c053-11e6-90e0-bfc75a5a664d.png)

**Comment by kdmsnr** [comment]
すみません、確認画面で止まってました
