### ISSUE TITLE
「キャンセル待ちに登録」の文字が切れている

### ISSUE THREAD

**Issue by kdmsnr** [doorkeeper/doorkeeper-support#46]
![screen shot 2016-12-20 at 20 33 42](https://cloud.githubusercontent.com/assets/23315/21349138/a175e038-c6f3-11e6-8030-3cdea977c529.png)

**Comment by pwim** [comment]
😮 大変に申しわけございませんでした。修正しました。

<img width="198" alt="fixed" src="https://cloud.githubusercontent.com/assets/30756/21384891/b3909aa8-c7af-11e6-874a-5190a0435b45.png">
