### ISSUE TITLE
エスケープしすぎ

### ISSUE THREAD

**Issue by kdmsnr** [doorkeeper/doorkeeper-support#48]
![screen shot 2017-05-10 at 22 54 14](https://cloud.githubusercontent.com/assets/23315/25902156/b722cd84-35d3-11e7-912b-652ce9b3fa0f.png)

**Comment by pwim** [comment]
報告ありがとうございました。先日、hamlをアップグレードしまして、エスケープが微妙に違います。正しく表示するように修正しました。
