### ISSUE TITLE
キャンセル待ちを繰り上げて申込終了日時を過ぎていたときに「申し込んでいたときの価格」で支払いできない。

### ISSUE THREAD

**Issue by kdmsnr** [doorkeeper/doorkeeper-support#7]
早期割引で申し込み
→ キャンセル待ち
→ 早期割引の締め切り
→ キャンセル待ちの繰り上げ
→ 早期割引で支払いできない

**Comment by pwim** [comment]
これは意図的なながれです。そのチケットの種類が売り期限になったので、買わなくなります。キャンセル待ちの際、チケットの種類を選ばないで申し込んだほうがいいと思いますが、現在のデーターモデルで簡単に出来ません。

**Comment by kdmsnr** [comment]
了解です
