### ISSUE TITLE
イベントページのサイドメニューにも「メンバー登録」がほしい

### ISSUE THREAD

**Issue by kdmsnr** [doorkeeper/doorkeeper-support#9]

**Comment by pwim** [comment]
人がそのイベントに行かないが、今度のイベントの誘いをもらうようになるためですよね。
確かにあると便利だと思います。
ですが、普通の参加者したい人も「メンバー登録」をクリックすることを心配しています。
ちょっと考えさせてください。

**Comment by pwim** [comment]
サイドメニューじゃなくて、登録フォームではどうでしょうか。以下にモックアップしました。

![Screen Shot 2013-04-09 at 2 30 41 PM](https://f.cloud.github.com/assets/30756/355363/bdac22c2-a0d6-11e2-9332-12dfa19edac9.png)

これがよかったら、日本語で何がいいと教えると、大変助かります。

**Comment by kdmsnr** [comment]
```
その日は都合が悪いという方は、[メンバー登録](member/new)をしていただけると次回のイベント開催時にメールで通知します。
```

**Comment by pwim** [comment]
了解しました。日本語を教えてありがとうございました。表示するように更新しました。

http://scrum-with-lego.doorkeeper.jp/events/3292
